### ISSUE TITLE
Can you provide a audio sample of this model inference?

### ISSUE THREAD

**Issue by BabaiLi** [nii-yamagishilab/ssnt-tts#2]
Hi! Thank you for this great Works!

Can you provide a audio sample of this model inference?
Japanese or English is OK.

**Comment by BabaiLi** [comment]
Ah, I found the audio sample in https://nii-yamagishilab.github.io/sample-ssnt-sampling-methods/, thanks.

**Comment by TanUkkii007** [comment]
Thanks, you found samples for the ICASSP paper.
By the way, here is a sample page for the SSW10 paper.
https://nii-yamagishilab.github.io/samples-ssnt/
